#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python viva-biofilm-equivalence.py

Figures are written to:  reports/notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # viva-biofilm: equivalence to a published biofilm model and viva-native capabilities
#
# _Investigation `viva-biofilm-equivalence` — coder reproduction notebook._
#
# **Question.** Can a clean-room Rust reimplementation of a published individual-based biofilm model (Cockx et al. 2024),
# wrapped as viva processes, reproduce the real engine's aggregate observables
# while unlocking composability, performance, reproducibility and rich visuals?
#
# An investigation that builds viva-biofilm (Rust + viva) and demonstrates,
# study by study, equivalence to the real iDynoMiCS-2 (via the pbg-idynomics2
# Java bridge) plus capabilities the Java tool lacks.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/home/runner/work/viva-biofilm/viva-biofilm').is_dir():
    REPO = Path('/home/runner/work/viva-biofilm/viva-biofilm')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from viva_biofilm.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

# ## Study: `chemostat-equivalence`
#
# **Question.** Does the viva-biofilm Rust ChemostatProcess reproduce iDynoMiCS-2's
# ChemostatSolver (first-order solute1 decay) to within 1% of the analytic
# solution 2·e^(−0.1t)?

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `chemostat-equivalence` | `chemostat-equivalence` | 601 | — |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `chemostat-equivalence`** — `spec_chemostat_equivalence` (a plain, editable dict)

from viva_superpowers.composite_spec import load_spec
spec_chemostat_equivalence = load_spec(REPO / 'viva_biofilm/composites/chemostat-equivalence.composite.yaml')
describe_spec(spec_chemostat_equivalence)

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: chemostat-equivalence ===
STUDY = 'chemostat-equivalence'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

# Runtime knobs — edit freely. STEPS = number of composite steps;
# INTERVAL = global dt filling ${interval} placeholders (a per-process
# interval pinned in the edit cell above takes precedence).
STEPS_chemostat_equivalence = 601
INTERVAL_chemostat_equivalence = 0.1

if RERUN:
    with quiet():  # the sim prints per-step progress; keep it out of the notebook
        # Generic process-bigraph protocol (no workspace runner detected):
        from viva_superpowers.composite_spec import build_composite_from_spec
        comp = build_composite_from_spec(spec_chemostat_equivalence, {'interval': INTERVAL_chemostat_equivalence}, core=core)
        comp.run(STEPS_chemostat_equivalence)  # writes the composite's declared emitter
    print(f'ran 1 simulation(s) -> {RUNS_DB}')
else:
    print("RERUN=False — rendering committed", RUNS_DB)

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **solute1 decay**

def _save_viz(study, slug, html):
    d = REPO / 'reports/notebooks/figures' / study
    d.mkdir(parents=True, exist_ok=True)
    out = d / (slug + '.html')
    out.write_text(html, encoding='utf-8')
    print('  wrote', out)


# solute1 decay
_save_viz('chemostat-equivalence', 'solute1_decay', _render_one('image:charts/decay.html', {'title': 'Chemostat equivalence', 'caption': 'viva vs analytic vs iDynoMiCS-2'}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | matches-analytic-within-1pct | kind=report_card_axis card=workspace/studies/chemostat-equivalence/viz/report_card group=chemostat-decay | op verdict_at_least level within_tol |
